# playbooks/provision-app.yml
---

- name: Deploy systemd unit for {{ app.name }}
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/spring-app.service.j2"
    dest: "/etc/systemd/system/{{ app.name }}.service"
    mode: '0644'
  vars:
    svc_name: "{{ app.name }}"
    jar_name: "{{ app.jar_name }}"
    svc_port: "{{ app.port }}"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart {{ app.name }}
  ansible.builtin.systemd:
    name: "{{ app.name }}"
    state: restarted

- name: Enable {{ app.name }} service
  ansible.builtin.systemd:
    name: "{{ app.name }}"
    enabled: yes
